# Generated by Django 3.2.5 on 2021-07-21 11:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('credits', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True, null=True)),
                ('pedagogy', models.TextField(blank=True, null=True)),
                ('expectation', models.TextField(blank=True, null=True)),
                ('textbook', models.TextField(blank=True, null=True)),
                ('refbook', models.TextField(blank=True, null=True)),
                ('pf_allowed', models.BooleanField(default=False)),
                ('project_details', models.TextField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('antireq', models.ManyToManyField(related_name='_courses_course_antireq_+', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_photo', models.ImageField(blank=True, null=True, upload_to='Faculty')),
                ('faculty_mail', models.EmailField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('reg_d_and_t', models.DateTimeField(default=django.utils.timezone.now)),
                ('teaching_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('syllabus_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('material_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('category_allotted', models.CharField(blank=True, choices=[('F', 'Foundation Programme'), ('G', 'General Education Requirements'), ('M', 'Major Course'), ('E', 'Free Electives')], max_length=1, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.person')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faculties',
            field=models.ManyToManyField(to='courses.Faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='prereq',
            field=models.ManyToManyField(related_name='_courses_course_prereq_+', to='courses.Course'),
        ),
    ]
