# Generated by Django 3.2.5 on 2021-08-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default='Sample Title', max_length=100),
            preserve_default=False,
        ),
    ]
