# Generated by Django 3.2.5 on 2021-08-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_photo',
            field=models.ImageField(default='Sample_Image.jpg', upload_to='Course'),
        ),
    ]
