# Generated by Django 3.2.5 on 2021-08-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_course_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_photo',
            field=models.ImageField(default='Samples/Sample_Image.jpg', upload_to='Course'),
        ),
    ]
