# Generated by Django 3.2.5 on 2021-08-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_course_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='pf_allowed',
            new_name='passFail_course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='antireq',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prereq',
        ),
        migrations.AddField(
            model_name='course',
            name='antirequisite_courses',
            field=models.ManyToManyField(blank=True, related_name='_courses_course_antirequisite_courses_+', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite_courses',
            field=models.ManyToManyField(blank=True, related_name='_courses_course_prerequisite_courses_+', to='courses.Course'),
        ),
    ]
