# Generated by Django 3.2.5 on 2021-08-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210808_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='refbook',
            new_name='reference_book',
        ),
    ]
