# Generated by Django 3.2.5 on 2021-08-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_refbook_course_reference_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_photo',
            field=models.ImageField(blank=True, default='Samples/Sample_Image.jpg', upload_to='Course'),
        ),
    ]
