# Generated by Django 3.2.5 on 2021-08-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_course_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='course',
            name='avg_material_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='avg_syllabus_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='avg_teaching_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
