# Generated by Django 3.2.5 on 2021-08-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20210820_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='material_rating',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='review_d_and_t',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='syllabus_rating',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='teaching_rating',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
