# Generated by Django 3.2.5 on 2021-08-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210820_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='review_d_and_t',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
