# Generated by Django 3.2.5 on 2021-07-21 11:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=200)),
                ('fdp_credits', models.IntegerField()),
                ('ger_credits', models.IntegerField()),
                ('major_credits', models.IntegerField()),
                ('freeElectives_credits', models.IntegerField()),
                ('durationYr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'I prefer not to say')], max_length=1)),
                ('phone_number', models.CharField(max_length=10)),
                ('college_mail', models.EmailField(max_length=254)),
                ('enr_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2021)])),
                ('fdp_credits_completed', models.IntegerField(default=0)),
                ('ger_credits_completed', models.IntegerField(default=0)),
                ('major_credits_completed', models.IntegerField(default=0)),
                ('freeElectives_credits_completed', models.IntegerField(default=0)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
