# Generated by Django 3.2.5 on 2021-08-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210815_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fdp_credits_completed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='freeElectives_credits_completed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='ger_credits_completed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='major_credits_completed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
